config:
  test_name: isic_test_ensemble
  test_dir: ../out/predictions/isic
  model_dir: #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k0/model_<timestamp>)
  split: ''
  seed: 20
  test_at: best
  others:
    model_dir:
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k1/model_<timestamp>)
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k2/model_<timestamp>)
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k3/model_<timestamp>)
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k4/model_<timestamp>)
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k5/model_<timestamp>)
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k6/model_<timestamp>)
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k7/model_<timestamp>)
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k8/model_<timestamp>)
      - #todo: add (e.g., ../out/isic/<timestamp>_isic_ensemble_k9/model_<timestamp>)
    test_at: best
  test_data:
    batch_size: 32
    dataset: ../in/datasets/isic_small/ISIC-2017_Test_v2
    num_workers: 1
    shuffle: false
    transform:
    - rescale:
        entries:
        - images
        - labels
        lower: 0
        upper: 1
    - permute:
        entries:
        - images
        - labels
        permutation:
        - 2
        - 0
        - 1
    - squeeze
meta:
  type: test-config
  version: 0
