config:
  test_name: brats_test_auxiliary_segm
  test_dir: ../out/predictions/brats
  model_dir: #todo: add (e.g., ../out/brats/<timestamp>_brats_auxiliary_segm/model_<timestamp>)
  split: ../config/splits/split_brats18_100-25-160.json
  seed: 20
  test_at: best
  others:
    is_log_sigma: false
  test_data:
    batch_size: 32
    dataset: ../in/datasets/brats18_test_wpred_reduced_norm.h5
    direct_extractor:
    - names
    - data:
        categories:
        - labels
    - files
    - properties
    - subject
    direct_transform:
    - squeeze:
        entries:
        - labels
    extractor:
    - indexing:
        do_pickle: true
    - shape
    - data:
        categories:
        - images
        - labels
    indexing:
      slice: {}
    num_workers: 0
    shuffle: false
    transform:
    - permute:
        permutation:
        - 2
        - 0
        - 1
    - squeeze
meta:
  type: test-config
  version: 0
